// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1XyZONXk5CbtLKBXg0dUG9KsJiRWCkGM',
    appId: '1:927811562748:web:f824284dd339c5c504bb79',
    messagingSenderId: '927811562748',
    projectId: 'musilux',
    authDomain: 'musilux.firebaseapp.com',
    storageBucket: 'musilux.firebasestorage.app',
    measurementId: 'G-CLMBZKME6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABN8UFCIaav0h1u7z_y-rcS6efqkm6yBc',
    appId: '1:927811562748:android:8532ea373d16cf2304bb79',
    messagingSenderId: '927811562748',
    projectId: 'musilux',
    storageBucket: 'musilux.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQWSbYZDGxAmB_OmrZ9bgjKv2EDb2iDPE',
    appId: '1:927811562748:ios:5e0623c235a4ad8504bb79',
    messagingSenderId: '927811562748',
    projectId: 'musilux',
    storageBucket: 'musilux.firebasestorage.app',
    iosBundleId: 'com.example.musilux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQWSbYZDGxAmB_OmrZ9bgjKv2EDb2iDPE',
    appId: '1:927811562748:ios:5e0623c235a4ad8504bb79',
    messagingSenderId: '927811562748',
    projectId: 'musilux',
    storageBucket: 'musilux.firebasestorage.app',
    iosBundleId: 'com.example.musilux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1XyZONXk5CbtLKBXg0dUG9KsJiRWCkGM',
    appId: '1:927811562748:web:7ab1a66873d5419d04bb79',
    messagingSenderId: '927811562748',
    projectId: 'musilux',
    authDomain: 'musilux.firebaseapp.com',
    storageBucket: 'musilux.firebasestorage.app',
    measurementId: 'G-2DYX24GP1P',
  );
}
